### ISSUE TITLE
create gulftalent_job_scraper.py file and return correct excel response by extracting jobs same as  in linkedin_scraper.py and indeed_scraper.py output file results.xlsx

### ISSUE THREAD

**Issue by bishaladhikari** [bishaladhikari/job-scraper-backend#1]
### Task Description
Need to write Gulftalent job fetching api
https://docs.google.com/spreadsheets/d/1O4B-orzMZVeAi-W0RIiDAosRoi5fvWxKEcyDOHi8sTY/edit#gid=0&range=A2

### What to do
create gulftalent_job_scraper.py file and return correct excel response by extracting jobs same as  in linkedin_scraper.py and indeed_scraper.py output file results.xlsx

**Comment by inirajbhandari** [comment]
@bishaladhikari 
**I created that file in order to prepare a scrapper but it been much more trouble to scrape due to some javascript and ajax requests 🥴.** 
So anyway firstly I created a separate file and prepare a scrapper class and I tried to dig into the website and finally I got a hidden API 😪.
Anyway, I prepared a flask entry point with a keyword and limit of response.
Something like this, ie: http://localhost:5000/gulftalent/accountant/10
**There is a class inside gulftalent_job_scrapper.py file,**
![image](https://user-images.githubusercontent.com/72457263/124417764-9aa1ac00-dd79-11eb-939f-c0a84ab37757.png)

and we can access that like this,
![image](https://user-images.githubusercontent.com/72457263/124417809-b7d67a80-dd79-11eb-8ee7-a466a35df172.png)


I don't know is it necessary, coz we have API but I have a separate branch so, shall I push or not?

**Comment by bishaladhikari** [comment]
@inirajbhandari 
I want to thank you for your time and effort that u have spent on carrying out the research..

Here is my thought.
We will use api for gulftalent like u suggested.
Here is the list of things that u need to be concerned
- [ ] since our frontend expects an excel file with the same headings like indeed and likedin the response from gulftalet api need to be converted to excel sheet.
- [ ] just like linkedin_job_scraper.py.main() is taking job title and output path as parameters, gulftalent_job_scraper.py will also take  these parameters.
- [ ] it will fetch the correct response by searching the title and u should conver it to excel accordingly.
I know this will require much efforts in ur part. So u can make list of things about what you are going to do w/ checkboxes. And we will review ur work accordingly and viewing ur evidence here.
Please feel free to ask if any doubt that u have. @leezene and I will assist u in the process. Cheers

**Comment by inirajbhandari** [comment]
@bishaladhikari 
As you mentioned, 

- [ ]  I created a method to pull jobs from gulftalent API related to that title and for now I just limited 10 web request.

![image](https://user-images.githubusercontent.com/72457263/124509915-7b933080-ddf2-11eb-8e29-e880fbcc7afc.png)
The code looks like this and once running the test from the direct function call,
Our response looks like this, 
![image](https://user-images.githubusercontent.com/72457263/124510386-67036800-ddf3-11eb-83f3-e111c74449ad.png)
- [ ] There is an entry point inside app.py as
![image](https://user-images.githubusercontent.com/72457263/124510132-ee041080-ddf2-11eb-8205-5754ca7c4a73.png)

But I am having an issue with converting that integer **posted date** to readable date format.

- [ ] Going to convert that integer date format to a human readable date string.

**Comment by bishaladhikari** [comment]
@inirajbhandari and @leezene 
Can u confirm the output of post date in results.xlsx when scraping linkedin and indeed is in same format?
I believe if it's in same format then the conversion of post date is already carried out in linkedin_job_scraper.py and you can copy that here.

And @inirajbhandari please call the gulftalent_job_scraper.main() in app.py same as linkedin_job_scraper.main()
@Suu-Zan Where are we at 
https://github.com/bishaladhikari/job-scraper-backend/issues/4. ?
We need domain url switching issue fixed before we can proceed with this one.

**Comment by leezene** [comment]
@inirajbhandari
Good work.

@bishaladhikari  https://github.com/bishaladhikari/job-scraper-backend/issues/1#issuecomment-874412441

Postdate is not as expected, on Postdate column in results.xlsx file, 
we need to have human readable format date, so when user downloads the excel file they can know in which date was the job posted. on LinkedIn and indeed date format as already on human readable form.

after than you can PR

**Comment by bishaladhikari** [comment]
@inirajbhandari 
After fixing post date conversion you can proceed to create the PR.
 Please refer to PR template #8 and dont forget to comment here. This is done in
- https://github.com/bishaladhikari/job-scraper-backend/issues/7#issuecomment-873761717
- also follow proper branch naming conventions. In your case it should be feature_1_niraj

**Comment by inirajbhandari** [comment]
@bishaladhikari 

**PR Link**
- #13 

**What I did**
added scraping rules for gulftalent 
**Affected areas**
app.py 

Supplement
n/a

**Comment by bishaladhikari** [comment]
@inirajbhandari 
### Review
- Overall changes look good to me.
- You need to name your branch accordingly. For this issue, it should have been feature_1_niraj. You can leave it as it is now. Please remember this in the future.

### Action To Do
- [ ] Resolve Conflicts
- [ ] Connect your PR to this issue
- [ ] Assign yourself in PR
- [ ] Request for at least 3 reviewers

**Comment by inirajbhandari** [comment]
@bishaladhikari 
Content Updated, 
Please review again ☺

**Comment by bishaladhikari** [comment]
@inirajbhandari 
Review done
