### ISSUE TITLE
The output file results.xlsx should be placed under output directory. 

### ISSUE THREAD

**Issue by bishaladhikari** [bishaladhikari/job-scraper-backend#26]
### Task description
Both the source and output are the same "results.xlsx" file so it's causing the conflicts. We have to write the output file to a separate directory so that we can put that in a gitignore.

### what to do
- [ ] source results.xlsx file should be unaffected by the output.
- [ ] write the results.xlsx to output directory
- [ ] download the output/results.xlsx file
