### ISSUE TITLE
Add a switch statement to give response based on the "domain"  in api request

### ISSUE THREAD

**Issue by bishaladhikari** [bishaladhikari/job-scraper-backend#4]
### Task Description
Add a switch statement for the domain. 
eg: ae.indeed.com, linkedin.com, gulftalent.com,etc

### Hints
    if 'linkedin' in domain:
        linkedin_job_scraper.main("linkedin.com", date_posted, title, loc, OUTPUT_DIR + 'results.xlsx')
    elif 'indeed' in domain:
        indeed_job_scraper.main("ae.indeed.com", date_posted, title, loc, OUTPUT_DIR + 'results.xlsx')
    else:
        gulftalent_job_scraper.main("gulftalent.com", date_posted, title, loc, OUTPUT_DIR + 'results.xlsx')

For eg the URL will be 
http://127.0.0.1:5000/?domain=ae.indeed.com&title=laravel%20developer&loc=dubai

### **Before**
-  http://127.0.0.1:5000/?title=laravel%20developer&loc=dubai
- all of the jobs are exported  in the same file results.xlsx.

### **After implementing this  feature**
-  http://127.0.0.1:5000/?domain=ae.indeed.com&title=laravel%20developer&loc=dubai
-  the file name will be like indeed_laravel_developer_timestamps.xlsx
### What to Do
- [ ]  domain in API request
- [ ] switch cases according to the incoming domain
- [ ] download file name according to the domain name(ae.indeed.com_laravel_developer.xlsx)

**Comment by bishaladhikari** [comment]
@Suu-Zan 
Please Estimate this

**Comment by bishaladhikari** [comment]
@Suu-Zan 
Please move the issue to Local In progress if you are working on it.

**Comment by bishaladhikari** [comment]
@Suu-Zan 
I have fixed the issue and  I am closing it
