### ISSUE TITLE
issue template

### ISSUE THREAD

**Issue by bishaladhikari** [bishaladhikari/job-scraper-backend#6]
### Task Description
Write about the task in details

**Before**
- what was happening before this issue.

**After implementing this  feature**
-  write list of the features  or fixes that will appear
### What to Do
- [ ]  domain in API request
- [ ] switch cases according to the incoming domain
- [ ] download file name according to the domain name(ae.indeed.com_laravel_developer.xlsx)

**Comment by bishaladhikari** [comment]
Local Evidence
post an image or video evidence on the Solution here

**Comment by bishaladhikari** [comment]
@bishaladhikari @leezene @inirajbhandari @Suu-Zan 
PR
- Link of the PR

Supplements
write other things that reviewers need to know when reviewing. For eg checkout to branch feature_4_bishal and try testing the feature

**Comment by bishaladhikari** [comment]
@(mention name of the assignee of the current issue)
### Review
My review is this.  I think this is supposed to be like this. You also need to care about following things and so on 

### Action To Do
- [ ] Do this
- [ ] Do that

**Comment by bishaladhikari** [comment]
@(mention name of the assignee of the current issue)
Review Done
